name: internal_localization_app
description: "A new Flutter package project."
version: 0.0.1


environment:
  sdk: '>=3.4.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  
  intl: ^0.18.0
  flutter_i18n: ^0.25.0
  # easy_localization: ^3.0.0
  flutter_translate: ^3.0.0
  flutter_localized_locales: ^1.0.0
  localize_and_translate: ^3.1.0
  flutter_localizations:
    sdk: flutter

## flutter pub run intl_utils:generate
## flutter pub run build_runner build

dev_dependencies:
  flutter_test:
    sdk: flutter
  # flutter_lints: ^3.0.0
  intl_utils: ^7.3.0
  localize_and_translate: ^3.1.0
  flutter_gen_runner: ^4.0.0
  build_runner: ^2.4.6
  # easy_localization_generator: ^2.0.0

flutter_gen:
  output: lib/gen/

flutter:
  assets:
    - assets/langs/
