name: env_data
description: "A new Flutter package project."
version: 0.0.1


environment:
  sdk: '>=3.4.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:


  assets:
    # - assets/fixture_data/
    - assets/.env
    - assets/env.env
